### ISSUE TITLE
DCOS integration for Windows unsupported

### ISSUE THREAD

**Issue by davidw93** [typesafehub/conductr-cli#227]
DCOS integration through `conduct setup-dcos` currently only supports Linux & Mac environments correctly.

https://github.com/dcos/dcos-cli/blob/master/dcos/subcommand.py#L396
Line 396 in subcommand.py (linked above) has a conditional statement to identify the BIN_DIRECTORY for Windows & non-Windows platforms. Non-Windows platforms are "bin" whereas Windows is "Scripts". 

Binary subcommands in the DCOS CLI for Windows also need to have the .exe extension see: https://github.com/dcos/dcos-cli/blob/master/dcos/subcommand.py#L113

I'll try and contribute a fix this week to this issue as it's relatively easy to put in place.

**Comment by huntc** [comment]
Thanks. I'm unsure how we will provide an exe though -our CLI at this point is a .py. We will shortly be using pyinstaller to build an exe, but haven't done so yet. 

Note that we also had to embed the dcos lib in our CLI. We did this because we needed to move on an issue that I believe is now fixed - so we can probably use the dcos lib as a dependency again.

**Comment by davidw93** [comment]
Adding .exe to the end of the binary copied to the bin directory worked sufficiently on my Windows 10 professional and Windows 7 professional machines. I will try this on another few machines before submitting any possible fixes.

I can confirm the newest DCOS lib works with the conductr-cli as I have tested all of this using the 1.8 release of the DCOS CLI.

**Comment by huntc** [comment]
Awesome - thanks again for looking at this.

**Comment by huntc** [comment]
Any progress on this @davidw93 ?
