### ISSUE TITLE
CLI packaging appears to cause issues with library version issues

### ISSUE THREAD

**Issue by longshorej** [typesafehub/conductr-cli#457]
The CLI uses `pyinstaller`  to create single file executables of `conduct`, `sandbox`, etc. This creates a temporary directory in `/tmp` when starting up. This seems to cause issues with some environments that have older (or newer?) libs installed than the system that built the CLI. In the case @edwardcallahan observed, when running on Xenial, when the bash process for the `start` script starts up, it first prints a warning about version issues. This causes the PID detection code in the agent to fail. To fix this, we need to ensure this warning is not printed by ensuring the proper libraries are being loaded and not those related to the `pyinstaller` build.

```
bash: /tmp/_MEIs5lfam/libtinfo.so.5: no version information available (required by bash))
```

There's a couple solutions we could employ:

1. Don't use `single-file` packaging for `pyinstaller` and instead package the contents similar to `check`. Perhaps this involves shipping an `.rpm`, `.deb`, `.dmg`, `.msi` instead of a ZIP so installation can be automated. **This would have an additional benefit of decreasing the startup time for the CLI tools as they don't have to unpack on every invocation.**
2. Investigate if ensuring that when the agent and core processes are started by the sandbox, that the `PATH` nor any library-related env variables do not include this `pyinstaller` (_MEI) directory. This directory is defined as `sys._MEIPASS`. **This may be the easier to implement.**

Relevant thread: https://typesafe.slack.com/archives/C03DUBYSE/p1494967311973698

**Comment by huntc** [comment]
I'd like to look at (2) with a longer term thought on (1). They are not mutually exclusive. There's not reason why `sys._MEIPASS` is required on the path once the CLI is launched, or at least when launching sub processes.

**Comment by fsat** [comment]
Turns out the problem is caused by `sys._MEIPASS` is being set into `LD_LIBRARY_PATH` environment variable when launching the agent.

Considering we’re launching a JVM based core and agent, I'm keen to ensure `sys._MEIPASS` is removed from both `LD_LIBRARY_PATH` and `PATH` environment variable when launching the core and agent.

If the user does set `LD_LIBRARY_PATH` and `PATH` environment variable set using `--env-core` and `--env-agent` flags, this will still need to be passed into the core and agent respectively, ignoring the `sys._MEIPASS`.

I think this would be a good solution to fix the issue - wdyt?

**Comment by longshorej** [comment]
Yeah, that sounds great to me.

**Comment by longshorej** [comment]
Fixed via https://github.com/typesafehub/conductr-cli/pull/458
