### ISSUE TITLE
Highlight the latest ConductR version from the sandbox

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#480]
Provide the facility to highlight the latest available version when using the sandbox.

**Comment by TimMoore** [comment]
It would be nice to have a command like `sandbox run latest` that could check an API to discover the latest version.

**Comment by markusjura** [comment]
Yes, I agree. Some history here: In the past, in order to use ConductR, the user needed to create a Lightbend account. Therefore, we forced the user to pick up the current ConductR version from lightbend.com. Now, ConductR can be used without a Lightbend account so we don't have this business restriction anymore and hence we are able to implement the `sandbox run latest` command.

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CLI notifications](https://trello.com/c/UYWVM6Rn/823-cli-notifications)

**Comment by fsat** [comment]
Fixed by #510

**Comment by fsat** [comment]
Actually, reopen - we don't have `sandbox run latest` just yet.
