### ISSUE TITLE
sandbox init command

### ISSUE THREAD

**Issue by fsat** [typesafehub/conductr-cli#98]
Implement sandbox init command that creates of a new docker VM image called `conductr` if not already present.

If VM not present, perform the following task:
- Create the said VM using `docker-machine`
- Configure the RAM required by the VM (so it can run Elasticsearch locally)

And then setup the environment variable required using `docker-machine env` command.

This will also mean the setup for `boot2docker` needs to be deprecated as `boot2docker` doesn't have the support required to create a VM with a specified name.

**Comment by huntc** [comment]
Related issue #97

**Comment by markusjura** [comment]
Yes, I guess we should only provide one command. Hence `conduct doctor` has more functions than `conduct init` I think we should use `conduct doctor`.

**Comment by huntc** [comment]
PR #99 addresses this. However I think we should now revert to using the `default` machine instead of `conductr`. After using the `init` command I found myself with both the `default` and `conductr` machines running. The problem with that is the 3GiB of memory that was consumed by having two machines running.

The `init` command should now just configure `default` for 2GiB if it has less than that, and create the image if it doesn't exist (as per current functionality).

**Comment by huntc** [comment]
@markusjura I think that `init` is nicer than `doctor` and more accurately describes what the command does perhaps. I also think that `doctor` could exist separately i.e. it isn't mutually exclusive.

**Comment by huntc** [comment]
BTW the current init command only allocates 2GiB whereas we recommend 3GiB on https://www.typesafe.com/product/conductr/developer. We should allocate 3GiB as ES is a thirsty beast.

**Comment by huntc** [comment]
cpus == 4 also requires adding. From the [developer page](https://www.typesafe.com/product/conductr/developer):

```
VBoxManage modifyvm default --memory 3072 --cpus 4
```

**Comment by fsat** [comment]
PR #102 addressed this
